### ISSUE TITLE
Normal issue

### ISSUE THREAD

**Issue by eansell3** [OxfordTechnicalSolutions/test_repo#4]
I'm an OxTS member and I have a problem.

**Comment by eansell** [comment]
comment

**Comment by eansell3** [comment]
another comment

**Comment by eansell3** [comment]
@eansell direct mention

**Comment by eansell3** [comment]
> 
> 
> comment

quotoe

**Comment by eansell4** [comment]
I shouldn't have permission to close this.
The [docs say I can't close this](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) with Read acess and the [access list from the owner's account](https://github.com/orgs/OxfordTechnicalSolutions/people/eansell4) says I only have Read access to this repository yet here I am closing it anyway.

**Comment by eansell4** [comment]
Hang on, it's still open! There was a "close with comment" button but it's still open!!! The button is gone, as it should be!!! No idea what happened but there is a God!!!!

Absolutely elated. Overwhelmed with relief

**Comment by eansell4** [comment]
Now I'm part of the support team, I can close it. Thank goodness it's working as intended
